# Core
RANKING_INPUT_ROOT = f"./_Raw Rankings_"
RANKING_OUTPUT_ROOT = f"."
TARGET_TAG = f"[rankerapp TARGET]"
TARGET_ROOT = f"../_Projects Hub_/{TARGET_TAG}"

# Ranker Utilities
INDEX_RANKING_FILE = f"{TARGET_ROOT}/{TARGET_TAG} Indexed Ranking.txt"
PLAYLISTS_CSV_FILE = f"{TARGET_ROOT}/{TARGET_TAG} Playlists CSV.txt"

# Music Utilities
FOLDERS_TO_PLAYLISTS_FOLDER = f"{TARGET_ROOT}/{TARGET_TAG} Folders to Playlists"
PLAYLISTS_FIXER_FOLDER = f"{TARGET_ROOT}/{TARGET_TAG} Playlists Fixer"

# Ranker - Input Raw
RANKING_ANIME_INPUT = f"{RANKING_INPUT_ROOT}/Ranking Anime - Raw.txt"
RANKING_FILM_INPUT = f"{RANKING_INPUT_ROOT}/Ranking Film - Raw.txt"
RANKING_MUSICA_CANZONI_INPUT = f"{RANKING_INPUT_ROOT}/Ranking Musica (Canzoni) - Raw.txt"
RANKING_MUSICA_ARTISTI_INPUT = f"{RANKING_INPUT_ROOT}/Ranking Musica (Artisti) - Raw.txt"

# Ranker - Output
RANKING_ANIME_FOLDER_OUTPUT = f"{RANKING_OUTPUT_ROOT}/Ranking Anime"
RANKING_FILM_FOLDER_OUTPUT = f"{RANKING_OUTPUT_ROOT}/Ranking Film"
RANKING_MUSICA_FOLDER_OUTPUT = f"{RANKING_OUTPUT_ROOT}/Ranking Musica"

RANKING_ANIME_OUTPUT = f"{RANKING_ANIME_FOLDER_OUTPUT}/Ranking Anime.txt"
RANKING_FILM_OUTPUT = f"{RANKING_FILM_FOLDER_OUTPUT}/Ranking Film.txt"
RANKING_MUSICA_CANZONI_OUTPUT = f"{RANKING_MUSICA_FOLDER_OUTPUT}/Ranking Canzoni.txt"
RANKING_MUSICA_ARTISTI_OUTPUT = f"{RANKING_MUSICA_FOLDER_OUTPUT}/Ranking Artisti.txt"
RANKING_MUSICA_CANZONIPERARTISTA_FOLDER_OUTPUT = f"{RANKING_MUSICA_FOLDER_OUTPUT}/Ranking Canzoni per Artista"
